version: 2.1


jobs:
  say-hello:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: |
            yum update -y && yum install -y python3 curl tar gzip && \
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
            python3 get-pip.py --user && \
            python3 -m pip install --user ansible
            curl --silent --location https://rpm.nodesource.com/setup_14.x | bash -
            yum install -y nodejs
      - run:
          name: Check NPM and Ansible versions
          command: |
            node --version
            npm --version
            ansible --version

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
