version: 2.1


jobs:
  say-hello:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: |
            apk add --update ansible tar gzip curl
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
