version: 2.1


jobs:
  say-hello:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: |
            export API_URL="http://127.0.0.1:3030"
            echo "${API_URL}"
            if (curl "${API_URL}" | grep "ok");
            then
              return 0
            else
              return 1
            fi

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
