version: 2.1


jobs:
  say-hello:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: |
            apk add --update ansible tar gzip curl

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
