version: 2.1  
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:  
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create CloudFormation Stack
          command: |
            aws cloudformation deploy \
              --template-file ec2instance.yml \
              --stack-name terry-${CIRCLE_WORKFLOW_ID:0:5}
              --region ${AWS_DEFAULT_REGION}

workflows:
  terry_cicd_workflow:
    jobs:
      - create_infrastructure
