version: 2.1


jobs:
  say-hello:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: |
            python3 -m pip install --user ansible 

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
