version: 2.1


jobs:
  say-hello:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: |
            aws --version
            echo "******* Checking EC2 IP ********"
            aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --filters "Name=tag:project,Values=terry-udapeople" \
              --output text >> ip.txt
            export BACKEND_IP=$(cat ip.txt)
            echo "******* Done Checking EC2 IP ********"
            echo ${BACKEND_IP}
            echo ${CIRCLE_WORKFLOW_ID:0:7}

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
